### PR TITLE
Update dapp libraries version, which fixes wallet connect modal issue

### LINKED ISSUE #114: Voting dApp - WalletConnect modal is not working consistently
If user selects connect with mobile then just closes the WalletConnect pop up, it doesn't seem to be possible to just select connect with mobile again. Page has to be refreshed.

**To reprodcue:**

1. Connect -> Concordium Mobile Wallet
2. Close the WalletConnect pop up
3. Connect -> Concordium Mobile Wallet

**Result**

WalletConnect pop up doesn't show up.

**Expected Result**

WalletConnect pop up should show up.

[04.04.2024_09.02.08_REC.mp4](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/6457b283-a3d2-4791-b7b3-b5dfab27c288/c50dfd40-4875-40f1-afa5-9c21978e2bc8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS82NDU3YjI4My1hM2QyLTQ3OTEtYjdiMy1iNWRmYWIyN2MyODgvYzUwZGZkNDAtNDg3NS00MGYxLWFmYTUtOWMyMTk3OGUyYmM4IiwiaWF0IjoxNzEyMjE1MTc0LCJleHAiOjMzMjgyNzc1MTc0fQ.SLXJW1J09iBJA-xT_GK4KvQBhB7wfvhAxK9YxeIWUpU)

### PR DESCRIPTION
**Pull request by soerenbf**
Closes #114 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: apps/voting/src/shared/wallet-connection.tsx [hunk 1]
```diff
@@ -125,7 +125,7 @@ function useWalletConnector(wc: WalletConnector): ConnectorContext {
                 );
 
                 if (temp === undefined) {
-                    return undefined;
+                    break outer;
```
Comment (abizjak) [inline apps/voting/src/shared/wallet-connection.tsx:128]: I don't understand this change.

Isn't the behaviour the same, since if this case is reached `conn` remains undefined.

Or am I reading the nesting wrong?

**Review by abizjak — APPROVED** [review]
