### PR TITLE
[Guardian app] various changes + fixes

### LINKED ISSUE #61: Guardian App -  Show error message if the app can't connect to the node
**Bug Description**
If the app was built with wrong build configuration, application will start but will not be able to connect to the node without any explanation.

**Steps to Reproduce**

1. Build app with `CCD_ELECTION_NODE="https://node.testnet.concordium.com:20000" # The node to use for queries`
2. Start the app.

**Expected Result**
Error message explaining the error since the app can't connect to the node.

**Actual Result**
Nothing happens except indicator is red.

**Versions**
- Software Version: 0.0.0

### LINKED ISSUE #62: Guardian app - network and contract indicators are not green while there seems to be connection to both
**Bug Description**
Tested on Windows.

It seems that the indicators are not working correctly. Importing account key that is not registered as Guardian throws error `Imported account is not a guardian in the election`, however indicators for network and the contract are grey.

**Steps to Reproduce**

1. Build app and run it on Windows with config parameters: 
```
CCD_ELECTION_CONTRACT_ADDRESS="<8011,0>"
CCD_ELECTION_NETWORK="testnet"
CCD_ELECTION_NODE="https://grpc.testnet.concordium.com:20000"
```

2. Import key that is not registered as Guardian.

**Expected Result**
Error shows up that account is not a guardian and indicators for connection to Testnet and to the contract are green.

**Actual Result**

Given that I get the error message makes me think  app has actually checked if my account is in the contract and I actually am connected but the indicators are not showing it.

image

**Versions**
- Software Version: 0.1.0
- OS: Windows

### LINKED ISSUE #66: Guardian app - better error handling if a guardian doesn't have enough CCDs to register keys
**Bug Description**
Attempt to register guardian public key while guardian didn't have enough CCDs to cover the cost fails but the error message could be presented better to the user.

**Steps to Reproduce**
Attempt to register public key while having 0 CCDs on account.

**Expected Result**
Nicer error message.

**Actual Result**
image

**Versions**
- Software Version:0.0.0
- OS:Windows

### LINKED ISSUE #71: Typo in Guardian App GUI text
**Description**
Please see attached image. "encryption shares" should be changed to "encrypted shares" 

image

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

### LINKED ISSUE #86: [Guardian app] don't use excluded guardians in the tally phase
**Task description**
With the implementation of #79, guardians can now be excluded in a tally phase re-run. This information is registered in the election contract, and should be taken into account when monitoring decryption status of peers in the guardian app.

### LINKED ISSUE #99: [Guardian app] Election flow is not interrupted in the guardian app in case of complain
In case one of the guardians file a complaint, guardian app will continue with the flow as nothing has happened. This means that once, voting is scheduled to start guardian app will transition in the state "Voting is ongoing" and afterwards transition to "Waiting for tally to be registered"

**To reproduce:**

1. Register invalid public key or invalid secret share for one of the guardians.
2. File a complain - complain was registered in the contract.
3. Wait for the time when voting should start and observe the guardian app.

**Result:**

Guardian app transitions further to states as election is ongoing.

**Expected:**

Guardian app would show that there was a problem in the setup phase and inform guardian that election can't proceed.

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

Various minor changes + fixes to the guardian application

Closes #86, fixes #99, fixes #61, fixes #62, fixes #66 fixes #71

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: apps/guardian/src/pages/Actions/SetupActions.tsx [hunk 1]
```diff
@@ -250,6 +250,22 @@ function Invalid() {
...
+ * Component shown when the election setup has not been completed prior to the election starting
+ */
+function Incomplete() {
+    return (
+        <>
+            <h3>Setup phase incomplete</h3>
+            <p>
+                The setup phase was not completed by one or more guardians.
+                <br />
+                Manual intervention by the election facilitator is required.
```
Comment (abizjak) [inline apps/guardian/src/pages/Actions/SetupActions.tsx:263]: Aren't we calling it "coordinator"?

**Review by abizjak — APPROVED** [review]

File: apps/guardian/src/pages/Actions/SetupActions.tsx (hunk 1 above)
Comment (soerenbf) [reply apps/guardian/src/pages/Actions/SetupActions.tsx:263]: Yes, will change
